// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Y_CfJF-ligT2shXY-62vximUqh72lrU',
    appId: '1:83655169564:web:40e2174a3556516a0371d9',
    messagingSenderId: '83655169564',
    projectId: 'romegini',
    authDomain: 'romegini.firebaseapp.com',
    storageBucket: 'romegini.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4D4faEgi13Cl_pVbcZJWTP73Q-ks0_fY',
    appId: '1:83655169564:android:9cdb47210b9c431e0371d9',
    messagingSenderId: '83655169564',
    projectId: 'romegini',
    storageBucket: 'romegini.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhtXdAZTJIvWuPRCO_HCGxqmFOOKIYyOE',
    appId: '1:83655169564:ios:86cf5cfd34b85b170371d9',
    messagingSenderId: '83655169564',
    projectId: 'romegini',
    storageBucket: 'romegini.firebasestorage.app',
    iosBundleId: 'com.example.romeGini',
  );
}
